## This file (Presentacion6.sage) was *autogenerated* from the file Presentacion6.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('Presentacion6')
_st_.blockbegin()
try:
 p=plot(cos(x),(x,-4*pi,10*pi),color='red',legend_label='$y_1(x)=\cos x$')
 p+=plot(cos(x-pi/4),(x,-4*pi,4*pi),color='green',legend_label='$y_2(x)=\cos( x-\pi/4)$')
except:
 _st_.goboom(252)
_st_.blockend()
try:
 _st_.plot(0, format='notprovided', _p_=p)
except:
 _st_.goboom(254)
_st_.endofdoc()
