## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file Uni_Simetrias.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10)## This file (Uni_Simetrias.sagetex.sage) was *autogenerated* from Uni_Simetrias.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('Uni_Simetrias', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
try:
 _st_.commandline(_sage_const_0 , r"""
sage: var('r,theta')
sage: U = CoordinatePatch((r,theta))
sage: F = DifferentialForms(U)
sage: x= DifferentialForm(F, 0, r*cos(theta))
sage: y= DifferentialForm(F, 0, r*sin(theta))
sage: w=(x^3+x*y^2-x+y)*y.diff()-(y^3+x^2*y-x-y)*x.diff()
sage: w[0].simplify_full()
sage: w[1].simplify_full()
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_11 )
try:
 _st_.inline(_sage_const_0 , latex(w[_sage_const_0 ].simplify_full()))
except:
 _st_.goboom(_sage_const_12 )
try:
 _st_.inline(_sage_const_1 , latex(w[_sage_const_1 ].simplify_full()))
except:
 _st_.goboom(_sage_const_12 )
try:
 _st_.commandline(_sage_const_1 , r"""
sage: G=SymmetricGroup(5)
sage: sigma=G([(1,2,3),(4,5)])
sage: sigma^2
sage: sigma^3
sage: sigma^6
sage: G.order()
sage: H=G.subgroup([sigma])
sage: H.order()
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_11 )
try:
 _st_.commandline(_sage_const_2 , r"""
sage: H.list()
sage: H.is_normal()
sage: G1=DihedralGroup(3)
sage: G1[-2]
sage: H1=G1.subgroup(G1[-2])
sage: H1.is_normal()
sage: G1.quotient(H1)
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_10 )
_st_.endofdoc()
