## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file uni6.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_183 = Integer(183); _sage_const_185 = Integer(185); _sage_const_186 = Integer(186); _sage_const_192 = Integer(192); _sage_const_290 = Integer(290); _sage_const_4 = Integer(4); _sage_const_355 = Integer(355); _sage_const_322 = Integer(322); _sage_const_190 = Integer(190); _sage_const_297 = Integer(297); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_302 = Integer(302); _sage_const_20 = Integer(20); _sage_const_50 = Integer(50); _sage_const_307 = Integer(307); _sage_const_6 = Integer(6)## This file (uni6.sagetex.sage) was *autogenerated* from uni6.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('uni6', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
try:
 _st_.commandline(_sage_const_0 , r"""
sage: t,omega=var('t,omega')
sage: assume(omega>0)
sage: T=function('T',t)
sage: T=desolve(T.diff(t,2)+omega^2*T,T,ivar=t)

""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.inline(_sage_const_0 , latex(T))
except:
 _st_.goboom(_sage_const_185 )
try:
 _st_.inline(_sage_const_1 , latex(omega))
except:
 _st_.goboom(_sage_const_186 )
try:
 _st_.commandline(_sage_const_1 , r"""
sage: k1,k2=var('k1,k2')
sage: solve(T.diff(t)(t=0),[k1,k2])
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_190 )
try:
 _st_.inline(_sage_const_2 , latex(T(k1=_sage_const_0 ,k2=_sage_const_1 )))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.commandline(_sage_const_2 , r"""
sage: x,y=var('x,y')
sage: r=sqrt(x^2+y^2)
sage: theta=atan2(y,x)
sage: rho,phi=var('rho,phi')
sage: r.diff(x)(x=rho*cos(phi),y=rho*sin(phi)).simplify_full()
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_290 )
try:
 _st_.commandline(_sage_const_3 , r"""
sage: r.diff(x,2)(x=rho*cos(phi),y=rho*sin(phi)).simplify_full()
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_297 )
try:
 _st_.commandline(_sage_const_4 , r"""
sage: theta.diff(x)(x=rho*cos(phi),y=rho*sin(phi)).simplify_full()
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_302 )
try:
 _st_.commandline(_sage_const_5 , r"""
sage: theta.diff(x,2)(x=rho*cos(phi),y=rho*sin(phi)).simplify_full()
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_307 )
try:
 _st_.commandline(_sage_const_6 , r"""
sage: theta.diff(y)(x=rho*cos(phi),y=rho*sin(phi)).simplify_full()
sage: r.diff(y)(x=rho*cos(phi),y=rho*sin(phi)).simplify_full()
sage: theta.diff(y,2)(x=rho*cos(phi),y=rho*sin(phi)).simplify_full()
sage: r.diff(y,2)(x=rho*cos(phi),y=rho*sin(phi)).simplify_full()
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_322 )
_st_.blockbegin()
try:
 P = RR[x]; (x,) = P._first_ngens(1)
 n=_sage_const_2 
 l=_sage_const_0 
 J= sum([(-_sage_const_1 )**k/factorial(k)/gamma(k+_sage_const_1 )*(x/_sage_const_2 )**(_sage_const_2 *k+n) for k in range(_sage_const_20 )])
 Ceros=J.roots()
 Ceros=[i[_sage_const_0 ] for i in Ceros if i[_sage_const_0 ]>_sage_const_0 ]
 t,theta,r=var('t,theta,r')
 u=cos(Ceros[l]*t)*cos(n*theta)*J(Ceros[l]*r)
 gra=[]
 Trans = Cylindrical('height', ['radius', 'azimuth'])
 z=var('z')
 Trans.transform(radius=r, azimuth=theta, height=z)
 aux=parametric_plot3d([-_sage_const_1 ,-_sage_const_1 ,t],(t,-_sage_const_1 ,_sage_const_1 ),opacity=_sage_const_0 )
 for j in range(_sage_const_50 ):
     gra=plot3d(u(t=_sage_const_2 *pi/Ceros[l]*j/_sage_const_50 ),(r,_sage_const_0 ,_sage_const_1 ),(theta,_sage_const_0 ,_sage_const_2 *pi),\
 transformation=Trans,viewer='tachyon')+aux
     str2='mem-'+str(j)
     #La sentencia siguiente guarda la gráfica
     #\texttt{gra} en el directorio MiDirectorio
     #Hay que descomentarla para que funcione.
     #gra.save('/MiDirectorio/'+str2+'.png')
 
except:
 _st_.goboom(_sage_const_355 )
_st_.blockend()
_st_.endofdoc()
