## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file Uni_Simetrias.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_420 = Integer(420); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_353 = Integer(353); _sage_const_p2 = RealNumber('.2'); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_18 = Integer(18); _sage_const_832 = Integer(832)## This file (Uni_Simetrias.sagetex.sage) was *autogenerated* from Uni_Simetrias.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('Uni_Simetrias', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
 from sympy import *
 x,y,y_n=symbols('x,y,y_n')
 y=Function('y')(x)
 y_n=Function('y_n')(x)
 y=exp(y_n)/x
 eq=Eq(y.diff(x)-(ln(x*y))**_sage_const_2 *x*y+y/x,_sage_const_0 )
 simplify(eq)
except:
 _st_.goboom(_sage_const_12 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(simplify(eq)))
except:
 _st_.goboom(_sage_const_14 )
_st_.blockbegin()
try:
 from sympy import *
 x,x_n=symbols('x,x_n')
 x_n=acos(x)
 y=Function('y')(x_n)
 Ecuacion=-y.diff()+_sage_const_1 /(sqrt(_sage_const_1 -x**_sage_const_2 ))*y
except:
 _st_.goboom(_sage_const_10 )
_st_.blockend()
try:
 _st_.inline(_sage_const_1 , latex(simplify(Ecuacion)))
except:
 _st_.goboom(_sage_const_12 )
_st_.blockbegin()
try:
 from sympy import *
 x=symbols('x')
 y=Function('y')(x)
 r=sqrt(x**_sage_const_2 +y**_sage_const_2 )
 theta=atan(y/x)
 Expr2=r.diff(x)/theta.diff(x)
 Expr3=Expr2.subs(y.diff(x),\
 (y**_sage_const_3 +x**_sage_const_2 *y-x-y)/(x**_sage_const_3 +x*y**_sage_const_2 -x+y))
 r,theta=symbols('r,theta',positive=True)
 Expr4=Expr3.subs([(y,r*sin(theta)),\
 (x,r*cos(theta))])
 Expr5=simplify(Expr4)
except:
 _st_.goboom(_sage_const_18 )
_st_.blockend()
try:
 _st_.inline(_sage_const_2 , latex(powsimp(Expr5)))
except:
 _st_.goboom(_sage_const_3 )
try:
 _st_.inline(_sage_const_2 , latex(powsimp(Expr5)))
except:
 _st_.goboom(_sage_const_3 )
try:
 _st_.inline(_sage_const_2 , latex(powsimp(Expr5)))
except:
 _st_.goboom(_sage_const_3 )
try:
 _st_.inline(_sage_const_2 , latex(powsimp(Expr5)))
except:
 _st_.goboom(_sage_const_3 )
_st_.blockbegin()
try:
 reset()
except:
 _st_.goboom(_sage_const_353 )
_st_.blockend()
try:
 _st_.commandline(_sage_const_0 , r"""
sage: r,theta=var('r,theta')
sage: U = CoordinatePatch((r,theta))
sage: F = DifferentialForms(U)
sage: x= DifferentialForm(F, 0, r*cos(theta))
sage: y= DifferentialForm(F, 0, r*sin(theta))
sage: w=(x^3+x*y^2-x+y)*y.diff()-(y^3+x^2*y-x-y)*x.diff()
sage: w[0].simplify_full()
sage: w[1].simplify_full()
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_12 )
try:
 _st_.inline(_sage_const_3 , latex(w[_sage_const_0 ].simplify_full()))
except:
 _st_.goboom(_sage_const_13 )
try:
 _st_.inline(_sage_const_4 , latex(w[_sage_const_1 ].simplify_full()))
except:
 _st_.goboom(_sage_const_13 )
_st_.blockbegin()
try:
 reset()
except:
 _st_.goboom(_sage_const_420 )
_st_.blockend()
try:
 _st_.commandline(_sage_const_1 , r"""
sage: G=SymmetricGroup(5)
sage: sigma=G([(1,2,3),(4,5)])
sage: sigma^2
sage: sigma^3
sage: sigma^6
sage: G.order()
sage: H=G.subgroup([sigma])
sage: H.order()
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_11 )
try:
 _st_.commandline(_sage_const_2 , r"""
sage: H.list()
sage: H.is_normal()
sage: G1=DihedralGroup(3)
sage: G1[-2]
sage: H1=G1.subgroup(G1[-2])
sage: H1.is_normal()
sage: G1.quotient(H1)
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_10 )
_st_.blockbegin()
try:
 from sympy import *
 x,theta=symbols('x,theta')
 y=Function('y')(x)
 x_n=cos(theta)*x-sin(theta)*y
 y_n=sin(theta)*x+cos(theta)*y
 Expr2=y_n.diff(x)/x_n.diff(x)
 Expr3=Expr2.subs(y.diff(),\
 (y**_sage_const_3 +x**_sage_const_2 *y-x-y)/(x**_sage_const_3 +x*y**_sage_const_2 -x+y))
 x_n,y_n=symbols('x_n,y_n')
 Expr4=Expr3.subs([(y, -sin(theta)*x_n+cos(theta)*y_n),\
 (x,cos(theta)*x_n+sin(theta)*y_n)])
 Expr5=simplify(Expr4)
except:
 _st_.goboom(_sage_const_16 )
_st_.blockend()
_st_.blockbegin()
try:
 
 Expr6=Expr5.subs(sin(_sage_const_2 *theta + pi/_sage_const_4 ),\
 sin(_sage_const_2 *theta)*sqrt(_sage_const_2 )+cos(_sage_const_2 *theta)*sqrt(_sage_const_2 ))
 Expr7=Expr6.subs(cos(_sage_const_2 *theta),\
 _sage_const_1 +(cos(theta))**_sage_const_2    )
 Expr8=Expr7.subs(cos(_sage_const_2 *theta),\
 _sage_const_1 +(cos(theta))**_sage_const_2 )
 Expr9=Expr8.subs(sin(_sage_const_2 *theta),\
 _sage_const_1 -(cos(theta))**_sage_const_2 )
except:
 _st_.goboom(_sage_const_13 )
_st_.blockend()
try:
 _st_.inline(_sage_const_5 , latex(simplify(Expr9)))
except:
 _st_.goboom(_sage_const_15 )
try:
 _st_.inline(_sage_const_5 , latex(simplify(Expr9)))
except:
 _st_.goboom(_sage_const_15 )
try:
 _st_.inline(_sage_const_5 , latex(simplify(Expr9)))
except:
 _st_.goboom(_sage_const_15 )
try:
 _st_.inline(_sage_const_5 , latex(simplify(Expr9)))
except:
 _st_.goboom(_sage_const_15 )
_st_.blockbegin()
try:
 reset()
except:
 _st_.goboom(_sage_const_832 )
_st_.blockend()
_st_.blockbegin()
try:
 x,y,epsilon = var('x,y,epsilon')
 x_n=cos(epsilon)*x-sin(epsilon)*y
 y_n=sin(epsilon)*x+cos(epsilon)*y
 xi=x_n.diff(epsilon)(epsilon=_sage_const_0 )
 eta=y_n.diff(epsilon)(epsilon=_sage_const_0 )
 p=plot([])
 for x_abs in srange(_sage_const_0 ,_sage_const_1 ,_sage_const_p2 ):
     p+=parametric_plot([x_n(x=x_abs,y=_sage_const_0 ),\
 y_n(x=x_abs,y=_sage_const_0 )], (epsilon,_sage_const_0 ,_sage_const_2 *pi))
 p+= plot_vector_field((xi,eta),(x,-_sage_const_1 ,_sage_const_1 ),\
 (y,-_sage_const_1 ,_sage_const_1 ))
except:
 _st_.goboom(_sage_const_14 )
_st_.blockend()
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_2 )
_st_.endofdoc()
